// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwvrlvimmljdtfptxrdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dnJsdmltbWxqZHRmcHR4cmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjc3MjksImV4cCI6MjA2NTcwMzcyOX0.YkJjRnf651xggPt251_lRtHw7ou-VzooPy7S2ZG-90c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);